name: french_date_formatter
description: "A very simple package to format date in french."
version: 0.0.1
homepage: https://github.com/Hery34/french_date_formatter

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



